---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
stringData:
  {{- with .Values.auth }}
  postgres-secret: "{{ .dbPassword }}"
  mq-user: "{{ .mqUser }}"
  mq-password: "{{ .mqPassword }}"
  {{- end }}
