apiVersion: v1
kind: Service
metadata:
  name: mq-server-svc
spec:
  selector:
    app: mq-server
  ports:
    - port: 8080
      targetPort: 8080
      name: mqsp1
    - port: 8081
      targetPort: 8081
      name: mqsp2