name: deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      MQ_CLIENT_IMAGE: 85.192.34.50:5000/mq-client:${{github.sha}}
      MQ_SERVER_IMAGE: 85.192.34.50:5000/mq-server:${{github.sha}}

    steps:
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add MCS.MailRU registry to Docker
        run: |
          sudo jq '. + {"insecure-registries": ["85.192.34.50:5000"]}' /etc/docker/daemon.json >daemon.json
          sudo mv daemon.json /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Login to registry
        run: |
          docker login 85.192.34.50:5000 --username registry --password ${REGISTRY_PASSWORD}
      - name: Build image
        run: |
          docker build -t ${MQ_CLIENT_IMAGE} -f client/Dockerfile client
          docker build -t ${MQ_SERVER_IMAGE} -f server/Dockerfile server
      - name: Push image
        run: |
          docker push ${MQ_CLIENT_IMAGE}
          docker push ${MQ_SERVER_IMAGE}

      - name: Set K8s context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: https://85.192.34.50:6443
          k8s-secret: ${{ secrets.KUBE_TOKEN }}

      - name: Deploy
        run: |
          cd chart
          helm upgrade --atomic \
                       --install \
                       --set mqClient.image=${MQ_CLIENT_IMAGE} \
                       --set mqServer.image=${MQ_SERVER_IMAGE} \ 
                       --set rabbitmq.auth.username=worker \
                       --set rabbitmq.auth.password=worker \
                       --set auth.dbPassword=hello \
                       --set auth.mqUser=worker \
                       --set auth.mqPassword=worker \
                       message-queue-release .